### PR TITLE
Generating dwell time map and point source response

### PR DESCRIPTION
**Pull request by Yong2Sheng**
The notebook is `Point_source_resonse.ipynb`.

The module is located in `src/SpacecrafPositionAttitude.py`

Please let me know if you have any questions or comments, thanks!

### CODE REVIEW

**Comment by ckarwin** [comment]
I started going through the PR. Nice work, Yong! It's a great start. 

I'm testing calculating the average Aeff for the Crab from the 2016 balloon flight, using the DC1 ori file as input. Currently, it's taking a very long time to run sc_frame, but I think this should actually be fairly quick. See below for more details. For reviewing the code, I've gotten as far as get_dwell_map. Overall, it's looking pretty good, aside from the comments given below. I'll try to get through the rest of the code by next week, and give more comments as needed. 

Comments on Notebook:

“To get the pointings you can run the classic COSIpy for spetral analysis and save the pointings as numpy array files (.npy).” 
The pointings can also be extracted with mimrec. But anyways, for the SMEX mission the pointings will be be calculated from the orbit, which is what TS and his student are working on. 

Please provide a brief description of what a “dwell time map” is, i.e. the amount of time COSI spent looking at each point on the sky. 

For all the examples where you run “some_method?” — it’s neat that the “?” has this function in python, but I think you don’t need to include this in the notebook. It just clutters things up. People can look in the source code or run help if they want to see this, i.e.
import module
help(module) 

numpy is imported twice. 

Comments on source code:

General:

Why is the module named SpacecrafPositionAttitude.py. It looks like there is a typo in “craf”. I would just call it SpacecraftPositionAttitude.py

All your method descriptions start with “It”, which I would remove. 

sc_frame:

xpoins, ypoins, zpoins 
I don’t really like the variable names. I think it’s better to use something more descriptive, albeit longer, i.e. x_pointings. Personal preference, though, I guess. 

“save” is not defined in the parameters. I would actually just save automatically, and not include this option, since it doesn’t hurt anything (file should be small).

You should first check that the user passed at least 2 arguments, and throw an error if not. 

Lines 80 - 88: This is very redundant, and the logic is a bit strange. The method requires at least 2 directions, so you should be able to simply do something like (after checking for at least 2 args):

if self.xpoins is not None:
	self.src_path = np.zeros(self.xpions.shape)
else:
	self.src_path = np.zeros(self.ypions.shape) 

The main conversion is performed starting at line 90. I tried running this using the balloon pointings from the DC1 ori file, and it takes forever. This is because you are converting each point one by one using a for loop, whereas you should convert the entire array at once. This will also make the code much more simple — essentially you should be able to make the conversion in 2 or 3 lines. 

Additionally, the for loops are not optimized. For example, you define src_coord at each iteration, but it never changes, so you should define it outside of the for loop. This is irrelevant though, since you should be doing array operations anyway. 

In general, if you need to use for loops, I would refrain from using “tqdm”. It’s not really necessary and can cause problems.

**Comment by israelmcmc** [comment]
Nice work @Yong2Sheng! I'm still going through the review of this PR, but wanted to share what I got so far.

I agree with all of @ckarwin's comments. Specifically about the speed of the transformation in sc_frame(), Yong did it like that because of a limitation of the scoords package I wrote. I haven't found a way for astropy to use multiple rotation matrices at a time when converting coordinates. When you convert multiple coordinates from e.g. galactic to icrs, you need a single rotation matrix, and that works just fine. But in this case, you need one matrice per coordinate, and the custom frame mechanism that SpacecraftFrame uses seems to break in that case. @Yong2Sheng for now you can do the transformation like this: e.g.

```
att = Attitude.from_axes(x = SkyCoord(l = xps[:,0] * u.deg, b = xps[:,1] * u.deg, frame = frame),
                         y = SkyCoord(l = yps[:,0] * u.deg, b = yps[:,1] * u.deg, frame = frame),
                        frame = frame)

pos_gal = SkyCoord(l = 20*u.deg, b = 10*u.deg, frame = frame)

pos_sc = SkyCoord(np.dot(att.rot.inv().as_matrix(), pos.cartesian.xyz.value),
                  representation_type = 'cartesian',
                  frame = SpacecraftFrame())
```

It should be pretty fast.

Another comment is that the inputs and output of the different modules should be SkyCoord objects. You have them already, instead of e.g. getting the lon/lat like this

```
lon_temp = src_in_sc.lon.degree
lat_temp = src_in_sc.lat.degree
```

You can just return `src_in_sc` directly. It makes the code cleaner, keeps the information about the units and reference frame, and makes it compatible with astropy.

Lastly, I run some tests on the pointings. I checked the rotation of the detector within each point, as well as the rate of rotations. See pics below. They look like a reasonable sampling to me, given the angular resolution of the balloon.
Unknown
Unknown-1

I'll keep digging and run some checks on the dwell time map...

**Comment by Yong2Sheng** [comment]
> I'm testing calculating the average Aeff for the Crab from the 2016 balloon flight, using the DC1 ori file as input. Currently, it's taking a very long time to run sc_frame, but I think this should actually be fairly quick. 

Now I apply the new method suggested by Israel and it runs much faster!

> For all the examples where you run “some_method?” — it’s neat that the “?” has this function in python, but I think you don’t need to include this in the notebook. It just clutters things up.

I only kept one line of `some_method?` for demostration

> numpy is imported twice.

Fixed

> “save” is not defined in the parameters. I would actually just save automatically, and not include this option, since it doesn’t hurt anything (file should be small).

Saving now is default.

> You should first check that the user passed at least 2 arguments, and throw an error if not.

Now it checks the if the inputs are in the correct format (number of necessary input, input object type)

> Lines 80 - 88: This is very redundant

Fixed

>  you define src_coord at each iteration, but it never changes, so you should define it outside of the for loop. 

Fixed

> I would refrain from using “tqdm”. It’s not really necessary and can cause problems. 

tqdm module is removed

> for now you can do the transformation like this: e.g.

This is applied

Other wording issues are fixed. If you find something that I missed or still need improvement, please let me know.

**Other fixes:**
1. The input coordinates are SkyCoord objects instead of numpy array
2. The name of the module is corrected

**Remaining issues**
1. Although not significant, it can't read the saved dwell time map.

**Future improvement**
1. Plotting the dwell time map will be added. --> not sure if it's necessary.

Thanks for all the comments!

**Review by ckierans — APPROVED** [review]
Pull request ran with no errors. I have some small stylistic comments, but I will save those for another time.

**Pull request merged**
